### ISSUE TITLE
补充：约束布局中的left属性和start/end属性不能一起用

### ISSUE THREAD

**Issue by YxmCute** [getActivity/AndroidCodeStandard#4]
- 如果用了 app:layout_constraintLeft_toLeftOf="parent"的话，那么约束右边的则用，app:layout_constraintRight_toRightOf="parent"，不要使用 _app:layout_constraintEnd_toEndOf="parent"_

当然：**还是如作者所讲应当首推start和end属性**

**Comment by getActivity** [comment]
收到，建议已采纳，文档已更新，多谢小伙子的建议。
