### ISSUE TITLE
关于颜色的部分命名规范有不同的看法

### ISSUE THREAD

**Issue by hewh7** [getActivity/AndroidCodeStandard#7]
![image](https://github.com/getActivity/AndroidCodeStandard/assets/37362695/79479918-7992-447e-a518-3fb966fbf7a7)
颜色命名这里我觉得有些不合理, 项目主题色, 按钮颜色这些项目固定用色还能用 功能用途 命名, 产品想改也是统一改, 其他颜色就该用颜色的rgb码命名, 设计那边出图给的也是rgb码, 不然如果一个颜色用在了一个textview的背景又用在了一个edittext的边框, 用描述怎么命名? 

图中说的"别人不知道我那个色值是干什么的, 看到我有写就引用了", 不应该就是这样吗? 颜色就是颜色本身, 没有额外描述是主题色, 按钮颜色的都是表明这个颜色本身的作用就是显示该颜色. 

期待看到回复!

**Comment by getActivity** [comment]
小伙子，用 RGB 命名可能在你看来是没什么问题，但是在我看来是有问题的，这并不代表一定谁错了，或者谁不对，我只是发表自己的想法，个人观点仅供参考，RGB 这种命名在我看来等同于《太阳能手电筒》，这样等同于给 Color 定了毫无意义的资源名称，和在布局直接写死是颜色值是没有区别，甚至比直接写死在布局还更加麻烦，开发者还需要在 Color 文件定义一个这样的值，那样做为什么不直接写死布局中呢？

**Comment by hewh7** [comment]
> 小伙子，用 RGB 命名可能在你看来是没什么问题，但是在我看来是有问题的，这并不代表一定谁错了，或者谁不对，我只是发表自己的想法，个人观点仅供参考，RGB 这种命名在我看来等同于《太阳能手电筒》，这样等同于给 Color 定了毫无意义的资源名称，和在布局直接写死是颜色值是没有区别，甚至比直接写死在布局还更加麻烦，开发者还需要在 Color 文件定义一个这样的值，那样做为什么不直接写死布局中呢？

对我来说区别不大, 主要有两点:
1. 有些颜色命名是需要用功能或者用途命名的, 一部分用资源文件一部分写死不统一;
2. 写布局的时候速度会快上一些, 比如#3D5799, 事先在布局里写好, 后面再遇到这个颜色, 基本写上3D就可以回车了;

颜色全部用功能或者用途命名在我这有个问题就是, 如果这个颜色#3D5799在项目中只有三处用到了, 一处是背景颜色, 一处是文本颜色和一处边框颜色, 这该怎么命名? 我一直想不到可以兼容的命名方式所以用得不多的颜色都是rgb命名

**Comment by hewh7** [comment]
![image](https://github.com/getActivity/AndroidCodeStandard/assets/37362695/240a5f9b-0262-4e9a-a80c-7d685eb324e6)
看到后面还有资源文件相关规范, 是我比较认可的方式, 但是跟前面的隔开了一段, 是不是整合起来会比较好?

**Comment by getActivity** [comment]
> 1. 有些颜色命名是需要用功能或者用途命名的, 一部分用资源文件一部分写死不统一;

小伙子，如果将所有颜色值，无论是否有特殊含义，都定义到 `colors.xml`，那么肯定会多叠加一部分工作量，能带来的好处是什么？

> 2. 写布局的时候速度会快上一些, 比如#3D5799, 事先在布局里写好, 后面再遇到这个颜色, 基本写上3D就可以回车了;

小伙子，对于这一点我不是很赞同，提升开发效率和代码规范是两回事，一个是矛，另一个是盾，代码规范要考虑的是代码写法带来的影响综合考虑，而不是单纯是因为为了提升开发效率单一的点而做，你往 `colors.xml` 定义 `<name="color_FF35BF30">#FF35BF30</color>`，就跟在往这里面定义 `1=1`，`2=2`、`3=3` 的效果是一样的，没有什么用，为了做而做。

**Comment by getActivity** [comment]
> 看到后面还有资源文件相关规范, 是我比较认可的方式, 但是跟前面的隔开了一段, 是不是整合起来会比较好?

小伙子，这个是单独的章节，我之前其实也考虑过分散到各个节点上去，但是最终没有那么做，我的想法是，这个本质上是属于资源硬编码的规范，像其他节点是介绍如何给资源名称如何规范命名，而资源硬编码不讲怎么给资源命名，而是讲哪些资源应该定义到 xml 文件中，哪些资源是可以直接在布局文件中写死。

**Comment by hewh7** [comment]
> 小伙子，对于这一点我不是很赞同，提升开发效率和代码规范是两回事，一个是矛，另一个是盾，代码规范要考虑的是代码写法带来的影响综合考虑，而不是单纯是因为为了提升开发效率单一的点而做，你往 `colors.xml` 定义 `<name="color_FF35BF30">#FF35BF30</color>`，就跟在往这里面定义 `1=1`，`2=2`、`3=3` 的效果是一样的，没有什么用，为了做而做。
这么看确实很有道理, 感谢解答~

> 小伙子，这个是单独的章节，我之前其实也考虑过分散到各个节点上去，但是最终没有那么做，我的想法是，这个本质上是属于资源硬编码的规范，像其他节点是介绍如何给资源名称如何规范命名，而资源硬编码不讲怎么给资源命名，而是讲哪些资源应该定义到 xml 文件中，哪些资源是可以直接在布局文件中写死。
嗯嗯, 理解了
