### ISSUE TITLE
插拔外接键盘或者扫描枪会出现内存泄露

### ISSUE THREAD

**Issue by qiefeimao** [getActivity/AndroidCodeStandard#8]
插拔外接键盘或者扫描枪会出现内存泄露

![Screenshot_2024-09-05-16-05-01-567_com hjq demo](https://github.com/user-attachments/assets/61ff4c5c-b26a-46e7-b63a-9f07b1e1de56)

**Comment by getActivity** [comment]
小伙子，该 issue 被打回，打回的原因如下：

* 这个问题是 AndroidProject 的问题，请前往 [AndroidProject/issues](https://github.com/getActivity/AndroidProject/issues) 提 issue

请重新提一个 issue 并纠正以上问题
